import {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_PHONE_NUMBER,
  LOGO_DIMENSIONS,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
  PAYMENT_CONFIG_APP_ID,
  PAYMENT_CONFIG_LOCATION_ID,
  PAYMENT_CONFIG_TOKEN_CLIENT_NAME,
  PAYMENT_CONFIG_TRANSACTION_FEE,
  PAYMENT_CONFIG_TRANSACTION_PERCENTAGE,
} from "./config";

export {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_PHONE_NUMBER,
  LOGO_DIMENSIONS,
  POINT_OF_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
  PAYMENT_CONFIG_APP_ID,
  PAYMENT_CONFIG_LOCATION_ID,
  PAYMENT_CONFIG_TOKEN_CLIENT_NAME,
  PAYMENT_CONFIG_TRANSACTION_FEE,
  PAYMENT_CONFIG_TRANSACTION_PERCENTAGE,
};
